### PR TITLE
Stories/unit requirements

### PR DESCRIPTION
**Pull request by nimashariatian**
as promised, here is another WIP for issue #13  
i specifically did not fully implement this all the way to get your feedback first. 

i also included the page object pattern for feature specs, so let me know what you think.
i have no problem reverting anything you don't find appealing :) 

also, do you think we can update the Rspec in the gems and add few more gems in the tests ?
i'm thinking capybara-screenshot . 

factory girl has also been renamed to factory bot, so we can take care of that as well.

### CODE REVIEW

**Comment by nimashariatian** [comment]
thanks for feedback @eanders :) 
i'll make the adjustments and continue working on this either on the evenings or on sunday

**Comment by eanders** [comment]
@nimashariatian could you see if merging the `release-11` branch into your code now fixes the travis issues?  Thanks!

**Comment by nimashariatian** [comment]
looks like specs passed

**Comment by eanders** [comment]
Excellent.  We threw in some code to allow some tests to run without actually talking to the warehouse db, which isn't setup in the test environment.

**Pull request closed without merging**
