### PR TITLE
New Column Options for Prioritized Client Columns (Last Seen, Open ES Enrollments, Open SO Enrollments)

### PR DESCRIPTION
**Pull request by dtgreiner**
[//]: # 'remove this if PR is for a release-* branch'
# _Please squash merge this PR_

## Description

Include a summary of the changes and a link to the related issue. List any dependencies that are required for this change.

## Type of change
[//]: # 'remove options that are not relevant'
- [X] New feature (adds functionality)

## Checklist before requesting review
- [X] I have performed a self-review of my code
- [X] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [X] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [X] My code follows the style guidelines of this project (rubocop)
- [X] I have updated the documentation (or not applicable)
- [ ] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

### CODE REVIEW

**Review by eanders — APPROVED** [review]
@dtgreiner I _think_ this looks good, can you add a screenshot of how this looks on the prioritization page?  (I'm unclear how we display JSONB fields.)

**Comment by dtgreiner** [comment]
> @dtgreiner I _think_ this looks good, can you add a screenshot of how this looks on the prioritization page? (I'm unclear 
how we display JSONB fields.)

Right now, the page is just listing the data in an array for these types of fields. Most of the current options using this are arrays of integer or single phrases (e.g. [1,2,3,4,5] or ['one', 'two', three']). I can look at setting the new fields up html lists, but there may be some complexity differentiating between the different new fields and old.

Screenshot 2024-05-08 at 3 32 48 PM

**Comment by eanders** [comment]
@dtgreiner let's at least change that to `.join('; ')` if the type is array or json b.  (maybe we should label this as an array instead of jsonb in the `prioritized_columns_data` method to differentiate from a hash?

**Comment by dtgreiner** [comment]
@eanders I've updated this page to display arrays with the join('; ')

Screenshot 2024-05-09 at 1 31 23 PM

**Pull request merged**
