### PR TITLE
Modal scroll

### PR DESCRIPTION
**Pull request by eanders**

### CODE REVIEW

**Comment by gigxz** [comment]
@eanders  you want me to test this on CAS, and if so how do I navigate somewhere that pulls up a long modal?

**Review by gigxz — APPROVED** [review]
Looks good to me but I didn't test. Not sure why the Gemfile changes are there.

**Comment by eanders** [comment]
@gigxz the gemfile changes are just for some security updates.  Snuck them in since there wasn't much else going on.

https://qa-cas.openpath.host/matches/4624

Click on the Edit link for Contacts and add a bunch of contacts.

**Comment by gigxz** [comment]
@eanders ok gotcha. looks good. that vertical scrollbar gutter is always a pain (but maybe not worth fixing here)

**Pull request merged**
